spring:
  application:
    name: portfolio-blog

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
